import Foundation

/// A passwordless Robin account.
public struct Account: Codable, Equatable, Sendable {
  /// Stable non-PII account identifier.
  public let id: String
  /// Human-readable account name shown during passkey ceremonies.
  public let name: String
  /// Verified email used only when magic links are enabled.
  public let verifiedEmail: String?
  /// Authorization roles granted to the account.
  public var roles: Set<Role>
  /// Account creation time.
  public let createdAt: Date

  /// Creates a passwordless account.
  ///
  /// - Parameters:
  ///   - id: A stable nonempty identifier. A random identifier is generated by default.
  ///   - name: The nonempty name presented during passkey registration.
  ///   - verifiedEmail: An optional email that the application has already verified.
  ///   - roles: The account's initial authorization roles.
  ///   - createdAt: The account creation time.
  /// - Throws: ``AuthError/invalidInput`` when the identifier, name, or email is invalid.
  public init(
    id: String = UUID().uuidString,
    name: String,
    verifiedEmail: String? = nil,
    roles: Set<Role> = [],
    createdAt: Date = Date()
  ) throws {
    let normalizedVerifiedEmail = verifiedEmail.flatMap(normalizedEmail)
    guard !id.isEmpty, !name.isEmpty,
      verifiedEmail == nil || normalizedVerifiedEmail != nil
    else { throw AuthError.invalidInput }
    self.id = id
    self.name = name
    self.verifiedEmail = normalizedVerifiedEmail
    self.roles = roles
    self.createdAt = createdAt
  }
}
